Remove sonarQubeMinVersion from sonar packaging maven plugin config
The build failed with
```
Error:  Failed to execute goal org.sonarsource.sonar-packaging-maven-plugin:sonar-packaging-maven-plugin:1.23.0.740:sonar-plugin (default-sonar-plugin) on project sonar-aemrules-plugin: 'sonarQubeMinVersion' property cannot be specified anymore. Please specify a valid minimum version of plugin api with 'pluginApiMinVersion' instead. -> [Help 1]
```

`sonarQubeMinVersion` should not be used. Instead,
`pluginApiMinVersion`can be used to declare the minimal RUNTIME sonar
version required.

See https://community.sonarsource.com/t/how-to-use-sonar-version-sonar-plugin-api-version-and-sonarqubeminversion/110483

> For most simple cases, the two versions are the same. You compile your plugin against version X.Y of the plugin API, using for example an API foo introduced in version X.Y. At runtime, your plugin can be installed in any Sonar product that is implementing at least version X.Y of the Sonar Plugin API. Otherwise, your plugin will crash when calling foo.
>
> There are advanced use cases where a plugin wants to use an API introduced in a new version of the Sonar Plugin API, but stay compatible with older Sonar products. Those plugins will often use reflection or other technics to not crash at runtime.
> In this case, you can manually force the minimal Sonar Plugin API version to an older value than the version you are compiling with.
>
> When using the `sonar-maven-packaging-plugin`, by default the minimal version is the same as the version of the `sonar-plugin-api` dependency.
> But if you are in the advanced use case I described earlier, you can override the minimal version using the property `pluginApiMinVersion`.

This commit removes `sonarQubeMinVersion`, which should cause the
`sonar-maven-packaging-plugin` to fall back to the version of the `sonar-plugin-api` dependency.